### ISSUE TITLE
Week 1 Homework

### ISSUE THREAD

**Issue by matthewspelman** [matthewspelman/ga-fewd#1]
I had issues getting the last three lines of code to display properly on the HTML output.

**Comment by matthewspelman** [comment]
I had issues getting the last three lines of code to display properly on the HTML output.

**Comment by RobF1011** [comment]
Nice work with this, very colorful!

Your issue lies on line 81 (https://github.com/matthewspelman/ga-fewd/blob/master/d02/cookie-recipe/recipe.html#L81)

At the end of the <a> tag, there's a ? instead of the closing "

If you fix that the rest of the text should display!

Aside from that, make sure to avoid multiple style tags. I would consolidate all CSS declarations. For example:

``` css
h1 {
    font-family:sans-serif;
    color: green;
    text-align: left;
}
```
